#!/bin/sh

#
# Gradle start up script for POSIX, generated by Gradle 8.x
#
# 修复说明（Android 16 适配版）：
# 1. 补齐 cygwin/darwin/msys/nonstop 变量初始化，避免在 Linux 下执行空命令
# 2. 修正 JVM 参数堆叠顺序（原脚本把 -Xmx64m 等传给了 Gradle 主程序，导致
#    "Unknown command-line option '-X'" 而完全无法构建）
#

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")
APP_HOME=$(cd "$(dirname "$0")" && pwd -P)

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

cygwin=false
darwin=false
msys=false
nonstop=false
case "$(uname -s)" in
    CYGWIN* )  cygwin=true  ;;
    Darwin* )  darwin=true  ;;
    MINGW* )   msys=true    ;;
    NonStop* ) nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
    if ! command -v java >/dev/null 2>&1 ; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found."
    fi
fi

if [ -n "$MAX_FD" ] && [ "$MAX_FD" = "maximum" ] ; then
    MAX_FD=$( ulimit -H -n 2>/dev/null || echo "1024" )
    if [ "$MAX_FD" != "unlimited" ] ; then
        ulimit -n "$MAX_FD" 2>/dev/null || true
    fi
fi

if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
    JAVACMD=$(cygpath --unix "$JAVACMD")
fi

if ! command -v xargs >/dev/null 2>&1 ; then
    die "ERROR: xargs is not available."
fi

# 先按「JVM 参数 -> 主类 -> 用户参数」的正确顺序堆叠
set -- \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

exec "$JAVACMD" "$@"
